name: Format & Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint==2.15.5
          pip install -r requirements.txt
      - name: Format with black
        run: |
          # stop the build if format is not correct
          echo "Running with " $(pip freeze | grep "black")
          python -m black --skip-string-normalization --skip-magic-trailing-comma --line-length 120 --check ./python/hidet ./tests
      - name: Lint with pylint
        run: |
          echo "Running with" $(pip freeze | grep "pylint")
          python -m pylint --rcfile ./scripts/lint/pylintrc -j $(nproc) ./python/hidet
