name: Python Tests

on:
  push:
#    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, gpu]
    container:
      image: nvidia/cuda:11.8.0-base-ubuntu20.04
      options: --gpus all
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          # stop the build if format is not correct
          python -m pytest -v ./tests
